import "./globals.css";
import Navbar from "../components/Navbar";
import Loader from "../components/topLoader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Loader />

        <main>{children}</main>
      </body>
    </html>
  );
}
